export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED'

export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED'

export const GET_CATEGORY_SUBS = 'GET_CATEGORY_SUBS'
export const GET_CATEGORY_SUBS_SUCCESS = 'GET_CATEGORY_SUBS_SUCCESS'
export const GET_CATEGORY_SUBS_FAILED = 'GET_CATEGORY_SUBS_FAILED'
