export const ADD_COUPON = 'ADD_COUPON'
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS'
export const ADD_COUPON_FAILED = 'ADD_COUPON_FAILED'

export const GET_COUPON = 'GET_COUPON'
export const GET_COUPON_SUCCESS = 'GET_COUPON_SUCCESS'
export const GET_COUPON_FAILED = 'GET_COUPON_FAILED'

export const DELETE_COUPON = 'DELETE_COUPON'
export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS'
export const DELETE_COUPON_FAILED = 'DELETE_COUPON_FAILED'

export const APPLIED_COUPON = 'APPLIED_COUPON'
export const APPLIED_COUPON_SUCCESS = 'APPLIED_COUPON_SUCCESS'
export const APPLIED_COUPON_FAILED = 'APPLIED_COUPON_FAILED'
