// product
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED'

export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED'

export const GET_RELATED = 'GET_RELATED'
export const GET_RELATED_SUCCESS = 'GET_RELATED_SUCCESS'
export const GET_RELATED_FAILED = 'GET_RELATED_FAILED'

export const GET_PRODUCT_COUNT = 'GET_PRODUCT_COUNT'
export const GET_PRODUCT_COUNT_SUCCESS = 'GET_PRODUCT_COUNT_SUCCESS'
export const GET_PRODUCT_COUNT_FAILED = 'GET_PRODUCT_COUNT_FAILED'

export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS'
export const GET_ALL_PRODUCT_FAILED = 'GET_ALL_PRODUCT_FAILED'

export const PRODUCT_RATING = 'PRODUCT_RATING'
export const PRODUCT_RATING_SUCCESS = 'PRODUCT_RATING_SUCCESS'
export const PRODUCT_RATING_FAILED = 'PRODUCT_RATING_FAILED'
