export const SEARCH_QUERY = 'SEARCH_QUERY'
export const SEARCH_QUERY_SUCCESS = 'SEARCH_QUERY_SUCCESS'
export const SEARCH_QUERY_FAILED = 'SEARCH_QUERY_FAILED'

export const PRODUCT_SEARCH = 'PRODUCT_SEARCH'
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS'
export const PRODUCT_SEARCH_FAILED = 'PRODUCT_SEARCH_FAILED'
