export const CREATE_PAYMENT_ITENT = 'CREATE_PAYMENT_ITENT'
export const CREATE_PAYMENT_ITENT_SUCCESS = 'CREATE_PAYMENT_ITENT_SUCCESS'
export const CREATE_PAYMENT_ITENT_FAILED = 'CREATE_PAYMENT_ITENT_FAILED'
