export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY'
export const CREATE_SUB_CATEGORY_SUCCESS = 'CREATE_SUB_CATEGORY_SUCCESS'
export const CREATE_SUB_CATEGORY_FAILED = 'CREATE_SUB_CATEGORY_FAILED'

export const GET_SUB_CATEGORIES = 'GET_SUB_CATEGORIES'
export const GET_SUB_CATEGORIES_SUCCESS = 'GET_SUB_CATEGORIES_SUCCESS'
export const GET_SUB_CATEGORIES_FAILED = 'GET_SUB_CATEGORIES_FAILED'

export const DELETE_SUB_CATEGORY = 'DELETE_SUB_CATEGORY'
export const DELETE_SUB_CATEGORY_SUCCESS = 'DELETE_SUB_CATEGORY_SUCCESS'
export const DELETE_SUB_CATEGORY_FAILED = 'DELETE_SUB_CATEGORY_FAILED'

export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY'
export const UPDATE_SUB_CATEGORY_SUCCESS = 'UPDATE_SUB_CATEGORY_SUCCESS'
export const UPDATE_SUB_CATEGORY_FAILED = 'UPDATE_SUB_CATEGORY_FAILED'

export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY'
export const GET_SUB_CATEGORY_SUCCESS = 'GET_SUB_CATEGORY_SUCCESS'
export const GET_SUB_CATEGORY_FAILED = 'GET_SUB_CATEGORY_FAILED'
