// LOGIN USER
export const LOGGIN_IN_USER = 'LOGGIN_IN_USER'
export const LOGGIN_IN_USER_SUCCESS = 'LOGGIN_IN_USER_SUCCESS'
export const LOGGIN_IN_USER_FAILED = 'LOGGIN_IN_USER_FAILED'
// CREATE OR UPDATE
export const CREATE_OR_UPDATE_USER = 'CREATE_OR_UPDATE_USER'
export const CREATE_OR_UPDATE_USER_SUCCESS = 'CREATE_OR_UPDATE_USER_SUCCESS'
export const CREATE_OR_UPDATE_USER_FAILED = 'CREATE_OR_UPDATE_USER_FAILED'

export const CURRENT_USER = 'CURRENT_USER'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAILED = 'CURRENT_USER_FAILED'

export const CURRENT_ADMIN = 'CURRENT_ADMIN'
export const CURRENT_ADMIN_SUCCESS = 'CURRENT_ADMIN_SUCCESS'
export const CURRENT_ADMIN_FAILED = 'CURRENT_ADMIN_FAILED'

export const NOTIFICATION_ORDER = 'NOTIFICATION_ORDER'
export const NOTIFICATION_ORDER_SUCCESS = 'NOTIFICATION_ORDER_SUCCESS'
export const NOTIFICATION_ORDER_FAILED = 'NOTIFICATION_ORDER_FAILED'

export const LOGOUT_IN_USER = 'LOGOUT_IN_USER'

// user profile
export const LOADING = 'LOADING'
export const GET_USER = 'GET_USER'
export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'
