const express = require('express')
const router = express.Router()
const authRoute = require('./auth.route')
const userRoute = require('./user.route')
const categoryRoute = require('./category.route')
const authorRoute = require('./author.route')
const supplierRoute = require('./supplier.route')
const subCategoryRoute = require('./subCategory.route')
const cloudinaryRoute = require('./cloudinary.route')
const productRoute = require('./product.route')
const couponRoute = require('./coupon.route')
const stripeRoute = require('./stripe.route')
const orderRoute = require('./order.route')
const provinceRoute = require('./province.route')
const wardRoute = require('./district.route')
const postRoute = require('./post.route')
const commentRoute = require('./comment.route')
const messageRoute = require('./message.route')

// router.use('/', uploadRoute)
router.use('/v1', cloudinaryRoute)
router.use('/auth', authRoute)
router.use('/user', userRoute)
router.use('/category', categoryRoute)
router.use('/author', authorRoute)
router.use('/supplier', supplierRoute)
router.use('/sub-category', subCategoryRoute)
router.use('/product', productRoute)
router.use('/coupon', couponRoute)
router.use('/payment', stripeRoute)
router.use('/order', orderRoute)
router.use('/province', provinceRoute)
router.use('/district', wardRoute)
router.use('/post', postRoute)
router.use('/comment', commentRoute)
router.use('/message', messageRoute)

module.exports = router
